### ISSUE TITLE
babel settings

### ISSUE THREAD

**Issue by kockok** [elemus/react-redux-todo-example#1]
I can see that there's a `.babelrc` file, however, why setting it to false in config files?
```
  const babelLoaderOptions = {
  babelrc: false,
  presets: [
    [
      'es2015',
      { modules: false },
    ],
    'react',
  ],
```
Should I just delete the `.babelrc` file? Thanks.

**Comment by elemus** [comment]
It's true that `.babelrc` file doesn't used for bundling process right now. I tried to store all settings in one place, but `.babelrc` is still needed for running tests. Removing this file will eliminate the possibility to use `npm run test` and `npm run coverage` commands.

I know that it's a bit redundant to keep almost a same settings in two different files. Right now I have two options to solve this problem: use [mocha-webpack](https://www.npmjs.com/package/mocha-webpack) or just simply move babel settings from webpack config to `.babelrc` file.

**Comment by kockok** [comment]
Thanks, I opted to use `.babelrc` instead.
